//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/MenuSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/MenuSchema.xsd", IsNullable=false)]
public partial class MenuSchema {
    
    private MenuSchemaMenu[] menuField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Menu")]
    public MenuSchemaMenu[] Menu {
        get {
            return this.menuField;
        }
        set {
            this.menuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/MenuSchema.xsd")]
public partial class MenuSchemaMenu {
    
    private string menuAdiField;
    
    private decimal fiyatiField;
    
    /// <remarks/>
    public string MenuAdi {
        get {
            return this.menuAdiField;
        }
        set {
            this.menuAdiField = value;
        }
    }
    
    /// <remarks/>
    public decimal Fiyati {
        get {
            return this.fiyatiField;
        }
        set {
            this.fiyatiField = value;
        }
    }
}
